### ISSUE TITLE
Flickering on dialog

### ISSUE THREAD

**Issue by rkmax** [ArthurClemens/polythene#44] opened 2017-06-02 14:01 UTC
I'm just testing the elements here http://arthurclemens.github.io/Polythene-examples/index.html#/dialog and found there's an small flickering when open:

- Long dialog
- Modal dialog with backdrop
- Modal dialog dark theme

I'm using Google Chrome 58.0.3029.110 (64-bit)

btw, i found this project awesome!

**Comment by ArthurClemens** [comment] 2017-06-02 14:03
Thanks rkmax!

Can you describe the flickering? For example, is it in the backdrop or in the text?

**Comment by rkmax** [comment] 2017-06-02 14:05
Sure, when you open the dialog they appear / disappear quickly, then finally they appear, let me record my desktop you can see better the issue

**Comment by rkmax** [comment] 2017-06-02 14:16
@ArthurClemens here you can see now happens https://youtu.be/t3gEw6BiR9I

**Comment by ArthurClemens** [comment] 2017-06-04 09:33
I can't reproduce this. Are you using Mac or Windows?

**Comment by ArthurClemens** [comment] 2017-06-18 20:18
Let me know if this still happens. I will close this issue for now.

**Closed by ArthurClemens** 2017-06-18 20:18 UTC
